### ISSUE TITLE
A question about the  "__anyhit__ah" in "cuda_test/gaussians_aabb.cu".

### ISSUE THREAD

**Issue by Riga2** [hugobl1/ray_gauss#1]
Hi, 

Nice work, and thank you for sharing it!

I have a question about the implementation of "__anyhit__ah" in "cuda_test/gaussians_aabb.cu".

During the forward process in training, the function "computeBufferForward" is used to calculate the "density_buffer" of each slab_space, which is easy to understand. However, during testing, it seems that this calculation is performed in "__anyhit__ah", and I found that the "r_2" value here is identical for every sample point in the same slab_space, which means the weights for each sample point are the same. Did I understand it correctly?

And I wonder why it differs from the forward process during training.

Very appreciate it if provide any clues.

![20HL WRF0BAS(F0H8E)(KRT](https://github.com/user-attachments/assets/ec6938e7-3564-4866-94b0-4a568ffb686a)

**Comment by Riga2** [comment]
Apologies, I missed the update of M_xhit_xgaus at the end of the for-loop. That clarifies my question.

Thank you again.

**Comment by hugobl1** [comment]
Thank you for your interest in our work. Indeed, `M_xhit_xgaus` is updated at the end of the for-loop with: `M_xhit_xgaus += M_d_dt;`.
