### ISSUE TITLE
Train on images with defocused regions using focus stacked macro photos

### ISSUE THREAD

**Issue by ultra-sonic** [hugobl1/ray_gauss#2]
First off, I just want to say I’m a huge fan of your work on ray_gauss - it’s absolutely phenomenal! 

We are currently trying to train gaussians splats on macro footage with lots of Depth of Field. We do focus stacking so that all objects are sharp in selected images, but also sometimes go out of focus.

Does ray_gauss model physical cameras properly so we could train sharp gaussians even for the parts that are sometimes out of focus?

thanks in advance!
Oliver

**Comment by hugobl1** [comment]
Dear Oliver,
Thank you for your interest in RayGauss. Regarding your question, our approach assumes that the camera used for acquiring the dataset is a pinhole camera. Additionally, our method does not explicitly account for cases where the camera's aperture size is non-negligible, resulting in out-of-focus areas in the image. Considering such cases could be the subject of a future extension of our work.

**Comment by ultra-sonic** [comment]
Hi Hugo,

got it! It makes total sense that a pinhole camera cannot model DoF.
Thanks a lot for your answer!

cheers
Oliver
