### ISSUE TITLE
*computeColorFromSH_float3* and *color_features*

### ISSUE THREAD

**Issue by MouseChannel** [hugobl1/ray_gauss#3]
I noticed that `color_features` was used instead of `computeColorFromSH_float3` in the code. 
Could you please tell me why it was done this way? 
And how much impact will this have on the final result?
THANKS!!

**Comment by hugobl1** [comment]
Hi MouseChannel,
In this version of the code, we precompute the color features before using the OptiX pipeline. This approach approximates the color of a Gaussian based solely on the vector between the camera center and the Gaussian's mean. It does not significantly affect the quality of reconstruction and eliminates the need to recompute the color each time we query the Gaussian.
